version: "3.9"

x-common-server: &common-server
  build:
    context: ../../build/ubuntu/server
    dockerfile: Dockerfile
  restart: unless-stopped
  deploy:
    resources:
      limits:
        memory: 4G
        cpus: "2.0"
      reservations:
        memory: 1G
        cpus: "0.5"
  environment:
    TZ: Asia/Ho_Chi_Minh

services:
  openvpn:
    image: workleast/openvpn
    container_name: openvpn
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - openvpn_data:/opt/Dockovpn_data
    networks:
      private_network:
        ipv4_address: ${PRIVATE_OPENVPN_IP:-172.20.0.112}
      external_network:
        ipv4_address: ${PUBLIC_OPENVPN_IP:-194.147.100.112}
    environment:
      TZ: Asia/Ho_Chi_Minh
      HOST_ADDR: 194.147.100.112
    sysctls:
      - net.ipv4.ip_forward=1

  private-ubuntu:
    container_name: private-ubuntu
    expose:
      - "22"
    networks:
      private_network:
        ipv4_address: ${PRIVATE_UBUNTU_IP:-172.20.0.100}
    restart: unless-stopped
    <<: *common-server

  external-ubuntu:
    container_name: external-ubuntu
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    networks:
      external_network:
        ipv4_address: ${EXTERNAL_UBUNTU_IP:-194.147.100.100}
    restart: unless-stopped
    <<: *common-server


volumes:
  openvpn_data:

networks:
  private_network:
    driver: bridge
    ipam:
      config:
        - subnet: ${PRIVATE_NETWORK_SUBNET:-172.20.0.0}/16

  external_network:
    driver: bridge
    ipam:
      config:
        - subnet: ${EXTERNAL_NETWORK_SUBNET:-194.147.100.0}/24
